# Generated by Django 5.1.3 on 2024-12-01 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 12, 1, 4, 53, 8, 381362, tzinfo=datetime.timezone.utc
                ),
                verbose_name="入库时间",
            ),
            preserve_default=False,
        ),
    ]
